# Generated by Django 2.2 on 2021-08-16 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_books', '0002_auto_20210815_1454'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='users_who_like',
            new_name='who_like',
        ),
    ]
